- name: Goblin
  creature_type: humanoid
  difficulty: 1
  xp_value: 25
  stats:
    strength: 8
    dexterity: 14
    constitution: 10
    intelligence: 10
    wisdom: 8
    charisma: 8
- name: Orc
  creature_type: humanoid
  difficulty: 3
  xp_value: 75
  stats:
    strength: 16
    dexterity: 12
    constitution: 16
    intelligence: 7
    wisdom: 11
    charisma: 10
- name: Skeleton
  creature_type: undead
  difficulty: 2
  xp_value: 50
  stats:
    strength: 10
    dexterity: 14
    constitution: 15
    intelligence: 6
    wisdom: 8
    charisma: 5
- name: Zombie
  creature_type: undead
  difficulty: 1
  xp_value: 25
  stats:
    strength: 13
    dexterity: 6
    constitution: 16
    intelligence: 3
    wisdom: 6
    charisma: 5
- name: Giant Spider
  creature_type: beast
  difficulty: 4
  xp_value: 100
  stats:
    strength: 14
    dexterity: 16
    constitution: 12
    intelligence: 2
    wisdom: 11
    charisma: 4
- name: Shadow Mastiff
  creature_type: monstrosity
  difficulty: 5
  xp_value: 150
  stats:
    strength: 16
    dexterity: 14
    constitution: 13
    intelligence: 5
    wisdom: 12
    charisma: 7
- name: Lich
  creature_type: undead
  difficulty: 15
  xp_value: 10000
  stats:
    strength: 11
    dexterity: 16
    constitution: 16
    intelligence: 20
    wisdom: 14
    charisma: 16