# --- Weapons ---
- name: Crude Dagger
  item_type: weapon
  slot: main_hand
  description: "A simple dagger with a chipped stone blade."
  properties: ["Finesse", "Light", "Thrown (range 20/60)"]
  damage: "1d4"
  damage_type: Piercing

- name: Rusty Sword
  item_type: weapon
  slot: main_hand
  description: "A shortsword, pitted with rust but still serviceable."
  properties: ["Finesse", "Light"]
  damage: "1d6"
  damage_type: Piercing

- name: Steel Longsword
  item_type: weapon
  slot: main_hand
  description: "A well-crafted longsword, the standard for knights and adventurers."
  properties: ["Versatile (1d10)"]
  damage: "1d8"
  damage_type: Slashing

- name: Gnarled Staff
  item_type: weapon
  slot: main_hand
  description: "A twisted, sturdy piece of wood that can be used as a quarterstaff."
  properties: ["Versatile (1d8)"]
  damage: "1d6"
  damage_type: Bludgeoning

- name: Elven Bow
  item_type: weapon
  slot: main_hand
  description: "A beautifully crafted longbow of yew, favored by elven archers."
  properties: ["Ammunition (range 150/600)", "Heavy", "Two-Handed"]
  damage: "1d8"
  damage_type: Piercing

- name: Orcish Greataxe
  item_type: weapon
  slot: main_hand
  description: "A heavy, brutal axe that requires immense strength to wield effectively."
  properties: ["Heavy", "Two-Handed"]
  damage: "1d12"
  damage_type: Slashing

# --- Armor ---
- name: Leather Tunic
  item_type: armor
  slot: chest
  description: "Padded leather armor."
  properties: ["Light Armor"]
  armor_class: 11 # 11 + Dex modifier

- name: Iron Chainmail
  item_type: armor
  slot: chest
  description: "A standard shirt of interlocking metal rings. Requires Strength 13."
  properties: ["Heavy Armor"]
  armor_class: 16

- name: Mage Robes
  item_type: clothing
  slot: chest
  description: "Simple robes, offering no real protection."
  properties: []
  armor_class: 10 # Base AC

- name: Dwarven Plate
  item_type: armor
  slot: chest
  description: "Masterfully crafted full plate armor. Requires Strength 15."
  properties: ["Heavy Armor"]
  armor_class: 18

- name: Elven Chain
  item_type: armor
  slot: chest
  description: "A light and flexible chain shirt of elven make."
  properties: ["Medium Armor"]
  armor_class: 14 # 14 + Dex modifier (max 2)

# --- Magical Items ---
- name: Ring of Protection
  item_type: wondrous_item
  slot: ring1
  description: "This ring grants a +1 bonus to AC and saving throws."
  properties: ["Requires Attunement"]
  stat_modifiers: {armor_class: 1, all_saving_throws: 1}

- name: Amulet of Wisdom
  item_type: wondrous_item
  slot: neck
  description: "This amulet grants a +1 bonus to the wearer's Wisdom score."
  properties: ["Requires Attunement"]
  stat_modifiers: {wisdom: 1}

- name: Gauntlets of Ogre Power
  item_type: wondrous_item
  slot: arms
  description: "These gauntlets set the wearer's Strength score to 19."
  properties: ["Requires Attunement"]
  stat_modifiers: {strength: 19}

- name: Boots of Speed
  item_type: wondrous_item
  slot: legs
  description: "While wearing these boots, you can use a bonus action to double your speed for 10 minutes."
  properties: ["Requires Attunement"]
