- type: Bounty
  title: "The <creature_name> of <dungeon_name>"
  description: "The local authorities have placed a bounty on the <creature_name>s infesting the <dungeon_name>. Clear them out for a reward."
  reward_template: "<random_gold> gold pieces"

- type: Fetch
  title: "The Lost <item_name> of <npc_name>"
  description: "<npc_name> of <location_name> has lost a precious <item_name>. They believe it was stolen and taken to the <dungeon_name>. Retrieve it for them."
  reward_template: "A magical item"

- type: Delivery
  title: "Urgent Missive to <destination_location>"
  description: "<giver_npc_name> of <start_location> needs an urgent message delivered to <receiver_npc_name> in <destination_location>. A reward is offered for a swift and discreet delivery."
  reward_template: "A pouch of rare herbs"